# Generated by Django 4.1 on 2024-02-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('predicted_character', models.CharField(max_length=10)),
                ('actual_character', models.CharField(max_length=10)),
            ],
        ),
    ]
