# Generated by Django 4.1 on 2024-02-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0004_alter_character_actual_character_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='actual_character',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
